name: "Deploy"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/typst/typst:latest
          options: -v ${{ github.workspace }}:/data
          run: |
            cd /data
            typst compile main.typ
            mkdir static
            cp main.pdf static/index.pdf

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./index.pdf

  deploy:
    environment:
      name: web
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
