name: "release"

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/typst/typst:latest
          options: -v ${{ github.workspace }}:/data
          run: |
            cd /data
            typst compile main.typ
      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ github.sha }}"
          tag_exists_error: true
          message: "${{ env.DATE }}-${{ github.sha }}"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ env.DATE }} ${{ github.sha }}"
          files: main.pdf
          tag_name: "${{ github.sha }}"
